name = "smartflow-trader"
main = "src/index.js"
compatibility_date = "2025-01-07"

# 环境变量
[vars]
TG_BOT_TOKEN = "your_telegram_bot_token"
TG_CHAT_ID = "your_telegram_chat_id"

# 定时任务
[[triggers]]
cron = "0 * * * *"   # 每小时执行一次

# 自定义域名配置（如果你有自己的域名）
# [routes]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"

# KV 存储配置（暂时注释掉，稍后添加）
# [kv_namespaces]
# { binding = "TRADE_LOG", id = "your_kv_namespace_id" }
