name = "smartflow-trader"
main = "src/index.js"
compatibility_date = "2025-01-07"

[vars]
TG_BOT_TOKEN = "your_telegram_bot_token"
TG_CHAT_ID = "your_telegram_chat_id"

[[triggers]]
cron = "0 * * * *"   # 每小时执行一次

[kv_namespaces]
{ binding = "TRADE_LOG", id = "your_kv_namespace_id" }
